spring.application.name=API-GATEWAY
server.port=8080

logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%highlight(%-5level)] [%cyan(%thread)] %magenta(%logger{15}) -%msg%n


eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webmvc.routes[0].id=ITEM-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ITEM-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/items/**

spring.cloud.gateway.server.webmvc.routes[1].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webmvc.routes[2].id=USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webmvc.routes[3].id=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webmvc.routes[4].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webmvc.routes[5].id=INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/inventory/**



management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
